"""trading journal schema

Revision ID: 51c8a494a701
Revises: 
Create Date: 2026-09-16 04:30:45.847599
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '51c8a494a701'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_pending', 'outbox', ['dispatched_at', 'id'], unique=False)
    op.create_table('system_health',
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('component')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('session_windows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_logins', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('mt5_login', sa.BigInteger(), nullable=False),
    sa.Column('broker_server', sa.String(length=120), nullable=False),
    sa.Column('broker_name', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('margin_mode', sa.String(length=10), nullable=False),
    sa.Column('sync_source', sa.String(length=16), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_deal_time_msc', sa.BigInteger(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mt5_login', 'broker_server', name='uq_account_login')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_at'), 'audit_logs', ['at'], unique=False)
    op.create_table('daily_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('pre_market', sa.Text(), nullable=True),
    sa.Column('post_market', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'note_date', name='uq_daily_note')
    )
    op.create_index(op.f('ix_daily_notes_user_id'), 'daily_notes', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_family_id'), 'sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_hash'), 'sessions', ['refresh_hash'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('setups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('checklist', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_setup_name')
    )
    op.create_index(op.f('ix_setups_user_id'), 'setups', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_name')
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('ea_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('install_code', sa.String(length=32), nullable=True),
    sa.Column('install_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('install_code_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key_id', sa.String(length=64), nullable=False),
    sa.Column('api_secret_hash', sa.Text(), nullable=False),
    sa.Column('api_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('previous_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('rotation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('secret_version', sa.Integer(), nullable=False),
    sa.Column('ea_version', sa.String(length=32), nullable=True),
    sa.Column('terminal_build', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_ip', sa.String(length=45), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('install_code')
    )
    op.create_index(op.f('ix_ea_installations_account_id'), 'ea_installations', ['account_id'], unique=False)
    op.create_index(op.f('ix_ea_installations_api_key_id'), 'ea_installations', ['api_key_id'], unique=True)
    op.create_index('ix_ea_status_seen', 'ea_installations', ['status', 'last_seen_at'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('trade_key', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('execution_notes', sa.Text(), nullable=True),
    sa.Column('lesson', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.SmallInteger(), nullable=True),
    sa.Column('followed_plan', sa.Boolean(), nullable=True),
    sa.Column('mistakes', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('setup_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trade_key', name='uq_journal_trade')
    )
    op.create_table('raw_deals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('deal_ticket', sa.BigInteger(), nullable=False),
    sa.Column('order_ticket', sa.BigInteger(), nullable=True),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('time_msc', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('entry', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('volume', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('sl', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('tp', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('swap', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('magic', sa.BigInteger(), nullable=True),
    sa.Column('digits', sa.SmallInteger(), nullable=False),
    sa.Column('reason', sa.String(length=16), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'deal_ticket', name='uq_raw_deal')
    )
    op.create_index('ix_raw_deals_account_time', 'raw_deals', ['account_id', 'time_msc'], unique=False)
    op.create_index('ix_raw_deals_position', 'raw_deals', ['account_id', 'position_id'], unique=False)
    op.create_table('screenshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('trade_key', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_screenshots_lookup', 'screenshots', ['account_id', 'trade_key'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deals_seen', sa.Integer(), nullable=False),
    sa.Column('deals_new', sa.Integer(), nullable=False),
    sa.Column('trades_built', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_runs_account', 'sync_runs', ['account_id', 'started_at'], unique=False)
    op.create_table('trade_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('trade_key', sa.String(length=80), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trade_key', 'tag_id', name='uq_trade_tag')
    )
    op.create_index('ix_trade_tags_lookup', 'trade_tags', ['account_id', 'trade_key'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('trade_key', sa.String(length=80), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('volume_opened', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume_closed', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('avg_exit_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('initial_sl', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('initial_tp', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('final_sl', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('swap', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('pips', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('mae_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('mfe_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('mae_r', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('mfe_r', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('session', sa.String(length=16), nullable=True),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=True),
    sa.Column('hour_of_day', sa.SmallInteger(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('pl_provisional', sa.Boolean(), nullable=False),
    sa.Column('reconstruction_ver', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trade_key', name='uq_trade_key')
    )
    op.create_index('ix_trades_account_opened', 'trades', ['account_id', 'opened_at'], unique=False)
    op.create_index('ix_trades_open', 'trades', ['account_id', 'status'], unique=False)
    op.create_index('ix_trades_symbol', 'trades', ['account_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_trades_trade_date'), 'trades', ['trade_date'], unique=False)
    op.create_table('trade_legs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('raw_deal_id', sa.BigInteger(), nullable=False),
    sa.Column('deal_ticket', sa.BigInteger(), nullable=False),
    sa.Column('leg_type', sa.String(length=6), nullable=False),
    sa.Column('volume', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('time_msc', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_legs_trade', 'trade_legs', ['trade_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_legs_trade', table_name='trade_legs')
    op.drop_table('trade_legs')
    op.drop_index(op.f('ix_trades_trade_date'), table_name='trades')
    op.drop_index('ix_trades_symbol', table_name='trades')
    op.drop_index('ix_trades_open', table_name='trades')
    op.drop_index('ix_trades_account_opened', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_trade_tags_lookup', table_name='trade_tags')
    op.drop_table('trade_tags')
    op.drop_index('ix_sync_runs_account', table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index('ix_screenshots_lookup', table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index('ix_raw_deals_position', table_name='raw_deals')
    op.drop_index('ix_raw_deals_account_time', table_name='raw_deals')
    op.drop_table('raw_deals')
    op.drop_table('journal_entries')
    op.drop_index('ix_ea_status_seen', table_name='ea_installations')
    op.drop_index(op.f('ix_ea_installations_api_key_id'), table_name='ea_installations')
    op.drop_index(op.f('ix_ea_installations_account_id'), table_name='ea_installations')
    op.drop_table('ea_installations')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_setups_user_id'), table_name='setups')
    op.drop_table('setups')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_family_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_daily_notes_user_id'), table_name='daily_notes')
    op.drop_table('daily_notes')
    op.drop_index(op.f('ix_audit_logs_at'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_health')
    op.drop_index('ix_outbox_pending', table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
