"""symbol specs, position linkage, daily pl, live default

Revision ID: 4cdf5cff89c5
Revises: 89574add08ed
Create Date: 2026-09-16 03:35:53.515971
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4cdf5cff89c5'
down_revision = '89574add08ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol_specs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_account_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('volume_min', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume_max', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume_step', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tick_value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('contract_size', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('digits', sa.SmallInteger(), nullable=False),
    sa.Column('trade_allowed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_account_id'], ['member_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_account_id', 'symbol', name='uq_symbol_spec')
    )
    op.create_index(op.f('ix_symbol_specs_member_account_id'), 'symbol_specs', ['member_account_id'], unique=False)
    op.add_column('copy_orders', sa.Column('master_position_id', sa.BigInteger(), nullable=True))
    op.create_index('ix_copy_member_position', 'copy_orders', ['member_account_id', 'master_position_id'], unique=False)
    op.add_column('member_accounts', sa.Column('realised_pl_today', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('member_accounts', sa.Column('realised_pl_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('system_settings', 'id',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'id',
               existing_type=sa.SMALLINT(),
               server_default=sa.text("nextval('system_settings_id_seq'::regclass)"),
               existing_nullable=False)
    op.drop_column('member_accounts', 'realised_pl_date')
    op.drop_column('member_accounts', 'realised_pl_today')
    op.drop_index('ix_copy_member_position', table_name='copy_orders')
    op.drop_column('copy_orders', 'master_position_id')
    op.drop_index(op.f('ix_symbol_specs_member_account_id'), table_name='symbol_specs')
    op.drop_table('symbol_specs')
    # ### end Alembic commands ###
