"""initial schema

Revision ID: 89574add08ed
Revises: 
Create Date: 2026-09-15 15:33:28.320819
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '89574add08ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('mt5_login', sa.BigInteger(), nullable=False),
    sa.Column('broker_server', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('margin_mode', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('publish_enabled', sa.Boolean(), nullable=False),
    sa.Column('copy_enabled', sa.Boolean(), nullable=False),
    sa.Column('magic_filter', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('symbol_filter', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('margin', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('free_margin', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mt5_login', 'broker_server')
    )
    op.create_table('system_health',
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('component')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_logins', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_at'), 'audit_logs', ['at'], unique=False)
    op.create_table('dead_letter_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('first_failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replayed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['replayed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_account_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('volume_opened', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume_closed', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('open_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('swap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['master_account_id'], ['master_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_account_id', 'position_id')
    )
    op.create_table('member_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('mt5_login', sa.BigInteger(), nullable=False),
    sa.Column('broker_server', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('free_margin', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mt5_login', 'broker_server')
    )
    op.create_index(op.f('ix_member_accounts_status'), 'member_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_member_accounts_user_id'), 'member_accounts', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_family_id'), 'sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_hash'), 'sessions', ['refresh_hash'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('copying_paused', sa.Boolean(), nullable=False),
    sa.Column('emergency_stop', sa.Boolean(), nullable=False),
    sa.Column('emergency_stop_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emergency_stop_by', sa.UUID(), nullable=True),
    sa.Column('emergency_halts_telegram', sa.Boolean(), nullable=False),
    sa.Column('live_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('live_activated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_single_row'),
    sa.ForeignKeyConstraint(['emergency_stop_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['live_activated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('bot_token_enc', sa.LargeBinary(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('master_account_id', sa.UUID(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('publish_types', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('display_timezone', sa.String(length=64), nullable=False),
    sa.Column('edit_in_place', sa.Boolean(), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_account_id'], ['master_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copy_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_account_id', sa.UUID(), nullable=False),
    sa.Column('copy_enabled', sa.Boolean(), nullable=False),
    sa.Column('sizing_mode', sa.String(length=32), nullable=False),
    sa.Column('fixed_lot', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('copy_multiplier', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('risk_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('fixed_money_risk', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reverse_trades', sa.Boolean(), nullable=False),
    sa.Column('copy_sl', sa.Boolean(), nullable=False),
    sa.Column('copy_tp', sa.Boolean(), nullable=False),
    sa.Column('copy_modifications', sa.Boolean(), nullable=False),
    sa.Column('copy_pending', sa.Boolean(), nullable=False),
    sa.Column('symbol_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_signal_age_sec', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_account_id'], ['member_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_account_id')
    )
    op.create_table('ea_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('master_account_id', sa.UUID(), nullable=True),
    sa.Column('member_account_id', sa.UUID(), nullable=True),
    sa.Column('install_code', sa.String(length=32), nullable=True),
    sa.Column('install_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('install_code_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key_id', sa.String(length=64), nullable=False),
    sa.Column('api_secret_hash', sa.Text(), nullable=False),
    sa.Column('api_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('secret_version', sa.Integer(), nullable=False),
    sa.Column('previous_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('rotation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ea_version', sa.String(length=32), nullable=True),
    sa.Column('terminal_build', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_ip', sa.String(length=45), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('MASTER','MEMBER')", name='ck_ea_kind'),
    sa.ForeignKeyConstraint(['master_account_id'], ['master_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_account_id'], ['member_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('install_code')
    )
    op.create_index(op.f('ix_ea_installations_api_key_id'), 'ea_installations', ['api_key_id'], unique=True)
    op.create_index('ix_ea_status_seen', 'ea_installations', ['status', 'last_seen_at'], unique=False)
    op.create_table('risk_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_account_id', sa.UUID(), nullable=False),
    sa.Column('max_daily_loss', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_daily_loss_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('max_trade_risk', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_lot', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('min_lot', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_simultaneous_trades', sa.Integer(), nullable=True),
    sa.Column('max_daily_trades', sa.Integer(), nullable=True),
    sa.Column('allowed_symbols', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('blocked_symbols', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('max_spread_points', sa.Integer(), nullable=True),
    sa.Column('max_slippage_points', sa.Integer(), nullable=True),
    sa.Column('trading_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_account_id'], ['member_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_account_id')
    )
    op.create_table('trade_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('master_account_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('ticket', sa.BigInteger(), nullable=True),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('order_ticket', sa.BigInteger(), nullable=True),
    sa.Column('deal_ticket', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('prev_stop_loss', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('prev_take_profit', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('swap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('magic_number', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('server', sa.String(length=120), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_ea_id', sa.UUID(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('ignore_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['master_account_id'], ['master_accounts.id'], ),
    sa.ForeignKeyConstraint(['source_ea_id'], ['ea_installations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_account_id', 'event_id', name='uq_trade_event_id')
    )
    op.create_index('ix_trade_events_account_time', 'trade_events', ['master_account_id', 'occurred_at'], unique=False)
    op.create_index('ix_trade_events_position', 'trade_events', ['position_id'], unique=False)
    op.create_index(op.f('ix_trade_events_processing_status'), 'trade_events', ['processing_status'], unique=False)
    op.create_index(op.f('ix_trade_events_ticket'), 'trade_events', ['ticket'], unique=False)
    op.create_index('ix_trade_events_type_time', 'trade_events', ['event_type', 'received_at'], unique=False)
    op.create_table('copy_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_event_id', sa.UUID(), nullable=False),
    sa.Column('master_trade_id', sa.UUID(), nullable=True),
    sa.Column('member_account_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=True),
    sa.Column('requested_lot', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('calculated_lot', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('final_lot', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sizing_mode', sa.String(length=32), nullable=True),
    sa.Column('sizing_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('master_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('execution_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('slippage_points', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.String(length=48), nullable=True),
    sa.Column('reject_detail', sa.Text(), nullable=True),
    sa.Column('broker_ticket', sa.BigInteger(), nullable=True),
    sa.Column('broker_retcode', sa.Integer(), nullable=True),
    sa.Column('execution_token', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['master_trade_id'], ['master_trades.id'], ),
    sa.ForeignKeyConstraint(['member_account_id'], ['member_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_event_id'], ['trade_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_event_id', 'member_account_id', name='uq_copy_event_member')
    )
    op.create_index('ix_copy_lease', 'copy_orders', ['lease_expires_at'], unique=False)
    op.create_index('ix_copy_member_time', 'copy_orders', ['member_account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_copy_orders_execution_token'), 'copy_orders', ['execution_token'], unique=True)
    op.create_index('ix_copy_status', 'copy_orders', ['status'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trade_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['trade_event_id'], ['trade_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_pending', 'outbox', ['dispatched_at', 'id'], unique=False)
    op.create_table('telegram_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('trade_event_id', sa.UUID(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rendered_text', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_event_id'], ['trade_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'trade_event_id', name='uq_tg_channel_event')
    )
    op.create_index('ix_tg_retry', 'telegram_messages', ['status', 'next_attempt_at'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_event_id', sa.UUID(), nullable=True),
    sa.Column('copy_order_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['copy_order_id'], ['copy_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_event_id'], ['trade_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exec_copy', 'execution_logs', ['copy_order_id', 'at'], unique=False)
    op.create_index('ix_exec_event', 'execution_logs', ['trade_event_id', 'at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exec_event', table_name='execution_logs')
    op.drop_index('ix_exec_copy', table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index('ix_tg_retry', table_name='telegram_messages')
    op.drop_table('telegram_messages')
    op.drop_index('ix_outbox_pending', table_name='outbox')
    op.drop_table('outbox')
    op.drop_index('ix_copy_status', table_name='copy_orders')
    op.drop_index(op.f('ix_copy_orders_execution_token'), table_name='copy_orders')
    op.drop_index('ix_copy_member_time', table_name='copy_orders')
    op.drop_index('ix_copy_lease', table_name='copy_orders')
    op.drop_table('copy_orders')
    op.drop_index('ix_trade_events_type_time', table_name='trade_events')
    op.drop_index(op.f('ix_trade_events_ticket'), table_name='trade_events')
    op.drop_index(op.f('ix_trade_events_processing_status'), table_name='trade_events')
    op.drop_index('ix_trade_events_position', table_name='trade_events')
    op.drop_index('ix_trade_events_account_time', table_name='trade_events')
    op.drop_table('trade_events')
    op.drop_table('risk_settings')
    op.drop_index('ix_ea_status_seen', table_name='ea_installations')
    op.drop_index(op.f('ix_ea_installations_api_key_id'), table_name='ea_installations')
    op.drop_table('ea_installations')
    op.drop_table('copy_settings')
    op.drop_table('telegram_channels')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_family_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_member_accounts_user_id'), table_name='member_accounts')
    op.drop_index(op.f('ix_member_accounts_status'), table_name='member_accounts')
    op.drop_table('member_accounts')
    op.drop_table('master_trades')
    op.drop_table('dead_letter_events')
    op.drop_index(op.f('ix_audit_logs_at'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_health')
    op.drop_table('master_accounts')
    # ### end Alembic commands ###
